<?php

namespace App\Http\Requests\user;

use App\Rules\PhoneRegex;
use Illuminate\Foundation\Http\FormRequest;

class UserUpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules(): array
    {
        return [
            'avatar' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:150',
            'name' => 'required|min:5|max:150',
            'email' => 'nullable|email|unique:users,email,id,' . $this->id,
            'phone' => [
                'nullable',
                'unique:users',
                new PhoneRegex(),
                'id'
            ],
        ];
    }

    public function messages(): array
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
